### ISSUE TITLE
libssl1.1 not found

### ISSUE THREAD

**Issue by Razerviper** [jkcoxson/DiOS-Instructions#17]
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /usr/local/bin/idevice_id
  Reason: image not found
zsh: abort      idevice_id

Libssl isn't there and I tried everything but it doesn't work for me :(
I know there is a closed one with same problem, the fixes didn't work for me

**Comment by Razerviper** [comment]
Researched some more, fixed it :)

**Comment by lumap** [comment]
what did you do to fix it?

**Comment by Razerviper** [comment]
> what did you do to fix it?

create a symlink at the specified location through terminal, https://pavcreations.com/dyld-library-not-loaded-libssl-1-1-dylib-fix-on-macos/
ln -s /usr/local/opt/openssl/lib/libssl.1.1.dylib
