### ISSUE TITLE
Oh man :((

### ISSUE THREAD

**Issue by Swifticul** [jkcoxson/DiOS-Instructions#9]
ERROR:
dyld[8778]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /usr/local/bin/idevice_id
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)
zsh: abort      idevice_id

weird because all the files are at these exact places 🤔 
maybe its Monterey with a new filesystem method, because a lib folder in local was absent. i had to make one myself

**Comment by jkcoxson** [comment]
If you have brew, install OpenSSL with brew and see if it fixes it. You might be able to find the libs it's looking for on the internet if you're against brew.

**Comment by Swifticul** [comment]
> If you have brew, install OpenSSL with brew and see if it fixes it. You might be able to find the libs it's looking for on the internet if you're against brew.

Do i need Xcode pre-installed?

ERROR: Failed during: /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools

**Comment by Swifticul** [comment]
Just realised i can manually download the set on Apple's own website

**Comment by Swifticul** [comment]
Oh, just realised I can install Libimobiledevice itself with Homebrew. that's actually far easier than manually moving the files into local/bin, ETC
